// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Akka")]
[assembly: AssemblyCopyrightAttribute("Copyright © Aaron Stannard 2013-2014")]
[assembly: AssemblyVersionAttribute("0.3.1.0")]
[assembly: AssemblyFileVersionAttribute("0.3.1.0")]
