// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("MarkedUp")]
[assembly: AssemblyCopyrightAttribute("Copyright © MarkedUp 2012-2014")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
